Dropper
G7DAO/protocol pull request #53
Opened 2024-08-27 16:06 UTC by mrk-hub

Migration of dropper v0.2.0 from Moonstream
Migration of Terminus from Moonstream
Migration of Diamonds from Moonstream
Creation of Dropper v0.3.0

2024-09-21 00:34 UTC, karacurt requested changes

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        LibSignatures._setEIP712Parameters("Game7 Dropper", "0.3.0");
**suggestion (non-blocking):** Shouldn't those values be received in `init` as parameters? That way, we can reuse this dropper code with other customers.

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenAddress = tokenAddress;
**issue (blocking):** Shouldn't we enforce a `tokenAddress` in case of a native token? maybe `address(0)`?

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenId = tokenId;
**issue (blocking):** Shouldn't we enforce a `tokenId` in the case of the native token? maybe `0`?

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +            //Amount change after safeTransferFrom only on erc721. Since amount is used as tokenId for erc721 transfers
**question:** I didn't understand this. Why is `amount` used as an ID instead of `claimToken.tokenId`?

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +    function withdrawERC20(address tokenAddress, uint256 amount) public onlyTerminusAdmin {
**suggestion (non-blocking):** Would it be good to add the `recipient` parameter in case we are withdrawing to another account? I don't know if we will have this use case, but that can be useful.

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +    bytes32 constant DROPPERV3_STORAGE_POSITION = keccak256("game7dao.eth.storage.Dropper");
**todo:** Just leaving this comment to help you remember if this needs to be changed before merge

2024-09-21 00:34 UTC, karacurt commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +// SPDX-License-Identifier: Apache-2.0
**suggestion:** 
Please double-check in other places to change our licenses to MIT
```suggestion
// SPDX-License-Identifier: MIT
```

2024-09-21 00:34 UTC, karacurt commented on web3/flows/DropperV3.md
> +Any account should be able to deploy a `DropperV3Facet` contract. The constructor should not revert.
**question:** Is this gonna be filled?

2024-09-21 00:34 UTC, karacurt commented on web3/hardhat.config.ts
> +  },
**issue (blocking):**  I think we can add an optimizer globally instead for just two files

2024-09-21 00:34 UTC, karacurt requested changes
Your branch has conflicts. Please remember to rebase-it before merging.

2024-09-22 18:58 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +// SPDX-License-Identifier: Apache-2.0
Thanks I need go through and complete this

2024-09-22 19:02 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        LibSignatures._setEIP712Parameters("Game7 Dropper", "0.3.0");
This is how the dropper from Moonstream was set. The Naming has no prevention. I see the EIP712Parameters in this case as the stamp of creation. Giving another location in the contract that says the contract is from Game7.

2024-09-22 19:05 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperClaimants.sol
> +    function drain(uint256 tokenType, address tokenAddress, uint256 tokenId) external onlyOwner {
Yes you are correct.

2024-09-22 19:26 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> + * @author Game7 World Builder team: worldbuilder - at - game7.io
Taken Thank you

2024-09-22 19:29 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenAddress = tokenAddress;
We can add in a statement requiring it set to address(0)

2024-09-22 19:36 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenId = tokenId;
tokenId is only being used on drop creation for ERC1155. Neither the ERC20 nor Native use it and ERC721 is unique tokenId for each claim. This is the logic from the moonstream repo I just transferred it with the migration and kept it the same with Native drop.

2024-09-22 19:39 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +            //Amount change after safeTransferFrom only on erc721. Since amount is used as tokenId for erc721 transfers
This is only the case for ERC721. I am assuming this is to prevent extra parameters being required when creating the signature and when comparing them. To limit the amount of gas being used by the claimant.

2024-09-22 19:48 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +    function withdrawERC20(address tokenAddress, uint256 amount) public onlyTerminusAdmin {
No we do not have the ability for someone else to claim a drop for someone else, or for you to send your drop to someone else. This would need to be discussed with the original devs on this part. I would suggest against it just incase of a frontend hack where the hackers just send everything to a hardcoded address. This happened on quickswap(uniswap clone) on matic a few years ago. The hackers just sent the tokens to be received to their address.

2024-09-22 19:49 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +    bytes32 constant DROPPERV3_STORAGE_POSITION = keccak256("game7dao.eth.storage.Dropper");
Need to ask Neeraj if this is what should be here or not.

2024-09-22 19:56 UTC, mrk-hub commented on web3/hardhat.config.ts
> +  },
This isn't recommended for default since optimizing can introduce bugs in seemingly correct code. So our default shouldn't be to optimize contracts. The Terminus Contract and DropperV3Facet need the optimization do to contract size.

2024-09-30 08:57 UTC, zomglings commented on web3/contracts/drops/dropper-V3/DropperClaimants.sol
> +contract ERC1155CompatibleClaimProxy is ClaimProxy {
This is just for tests @karacurt .

2024-09-30 08:59 UTC, zomglings commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        LibSignatures._setEIP712Parameters("Game7 Dropper", "0.3.0");
@karacurt : I prefer to do it this way - keeps things simple and I have been using versions to key storage migrations on other diamonds so I'd prefer to have a bit more control on these.

We do have users who have made customizations to DropperV2 - they simply wrote their own init function.

2024-09-30 09:00 UTC, zomglings commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenAddress = tokenAddress;
Doesn't matter to me either way. It is a nice user protection, as long as you put a useful error message @mrk-hub .

2024-09-30 09:02 UTC, zomglings commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +    function withdrawERC20(address tokenAddress, uint256 amount) public onlyTerminusAdmin {
This is not a claim - this is an admin function used to manage funds on the contract. I like @karacurt 's suggestion, but I also don't think it's a high priority.

2024-09-30 09:03 UTC, zomglings commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +    function withdrawERC20(address tokenAddress, uint256 amount) public onlyTerminusAdmin {
The easiest way to take funds off of the contract as an admin is to sign a message authorizing yourself to claim those tokens. In that sense, I don't even think the `withdraw*` functionality is necessary.

2024-09-30 09:03 UTC, zomglings commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +    bytes32 constant DROPPERV3_STORAGE_POSITION = keccak256("game7dao.eth.storage.Dropper");
What did we decide upon?

2024-09-30 09:04 UTC, zomglings commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +// SPDX-License-Identifier: Apache-2.0
Yeah, Moonstream contracts were Apache-2.0 but we are using MIT for the protocol contracts.

2024-09-30 09:04 UTC, zomglings commented on web3/flows/DropperV3.md
> +Any account should be able to deploy a `DropperV3Facet` contract. The constructor should not revert.
What do you mean?

2024-10-01 13:25 UTC, mrk-hub commented on web3/hardhat.config.ts
> +  },
The optimizer is needed for the terminus contract. I can look into the terminus to see if there is any changes I could make.

2024-10-01 13:26 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/LibDropperV3.sol
> +    bytes32 constant DROPPERV3_STORAGE_POSITION = keccak256("game7dao.eth.storage.Dropper");
I believe it was remove the .eth portion will push that change

2024-10-01 13:27 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +    function withdrawERC20(address tokenAddress, uint256 amount) public onlyTerminusAdmin {
Should we remove all the withdraw functions then?

2024-10-01 13:27 UTC, mrk-hub commented on web3/contracts/drops/dropper-V3/DropperV3Facet.sol
> +        tokenMetadata.tokenAddress = tokenAddress;
Understood

2024-10-01 13:30 UTC, mrk-hub commented on web3/contracts/dropper-V3/DropperV3Facet.sol
> +        uint256 maxNumberOfTokens,
On ERC721 it transfers the tokenId changes the amount to 1 and then handles the count. So if they plan on distributing 1000 ERC721 they set it to 1000 then the system handles it.

2025-07-09 17:23 UTC, closed without merging